---
- hosts: dev
  become: true

  tasks:
  - name: Remove softwares on redhat
    yum:
      name: "{{ item }}"
      state: absent
    loop:
    - nginx
    - git
    when: inventory_hostname in groups['test']

  - name: Install on ubuntu
    apt:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - git
    - docker
    when: inventory_hostname in groups['dev']


