---
- hosts: all

  tasks:
  - name: Copy files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: "{{ item.mode }}"
    loop:
    - { src: "/home/saksham/playbooks", dest: "/backup", owner: "saksham", group: "cloud", mode: "770" }
    - { src: "/home/saksham/chatapp", dest: "/home", owner: "sakar", group: "broadway", mode: "750" }
